apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: fdx-ri-dev-kube-hc
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 15
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /health
    port: 8080
